#!/usr/bin/env bash
# Records the same question twice in real Claude Code sessions that differ by one thing, the
# clear-claude plugin. Joining the two recordings side by side is edit.mjs's job.
#
# usage: demo/record-pair.sh <slug> "<question>"
#        writes <slug>-{before,after}.tape, frames-<slug>-{before,after}/ and
#        <slug>-{before,after}.words
#
# Both arms run stock Claude Code: no user settings (--setting-sources project) and no
# CLAUDE.md (CLAUDE_CODE_DISABLE_CLAUDE_MDS=1). The after arm adds --plugin-dir and nothing else.
# The word counts on the banners are read from the transcripts of the two sessions that were
# just recorded, so the number shown is the number of words on screen.
set -euo pipefail
slug="$1"; question="$2"; fps="${FPS:-12}"
cd "$(dirname "$0")"
. ./env.sh
# A clean clone of this repository on main, already trusted in Claude Code. See README.md.
demo_repo="${DEMO_REPO:-$HOME/demo/clear-claude}"
demo_cd="${DEMO_CD:-~/demo/clear-claude}" # as typed in the tape, so no absolute path is committed
# Claude Code names a project's transcript folder after its native path.
project="$demo_repo"
if command -v cygpath > /dev/null; then project="$(cygpath -w "$demo_repo")"; fi

tape() { # <arm> <claude command>
  cat > "$slug-$1.tape" <<TAPE
# $1 arm of: $question
# Generated by record-pair.sh. The hidden line only changes directory and switches CLAUDE.md
# discovery off; everything after Show is what the viewer sees being typed.
Output frames-$slug-$1/
Set Shell "bash"
Set FontSize 14
Set Width 690
Set Height 940
Set Padding 14
Set Framerate $fps
Set TypingSpeed 35ms
Hide
# VHS on Windows can drop the first keystroke; a leading space is harmless to bash.
Type " cd $demo_cd && export CLAUDE_CODE_DISABLE_CLAUDE_MDS=1 && clear"
Enter
Sleep 1s
Show
Type "$2"
Sleep 600ms
Enter
Sleep 8s
Type "$question"
Sleep 600ms
Enter
Sleep 26s
TAPE
}

tape before "claude --setting-sources project"
tape after  "claude --setting-sources project --plugin-dir plugins/clear-claude"
for arm in before after; do
  rm -rf "frames-$slug-$arm"
  vhs "$slug-$arm.tape" > "$slug-$arm.log" 2>&1
  node words.mjs "$project" > "$slug-$arm.words"
done
echo "$slug: $(cat "$slug-before.words") -> $(cat "$slug-after.words") words. Next: node demo/edit.mjs"
