#!/usr/bin/env bash
# Records the same question twice in real Claude Code sessions that differ by one thing,
# the clear-claude plugin, and joins the two recordings side by side.
#
# usage: demo/record-pair.sh <slug> "<question>"        record both arms, then assemble
#        ASSEMBLE_ONLY=1 demo/record-pair.sh <slug> ""  re-assemble frames already recorded
#
# Both arms run stock Claude Code: no user settings (--setting-sources project) and no
# CLAUDE.md (CLAUDE_CODE_DISABLE_CLAUDE_MDS=1). The after arm adds --plugin-dir and nothing else.
# Nothing in the terminal area is drawn or edited. The banner above it is a caption, and its
# word counts are read from the transcripts of the two sessions that were just recorded.
set -euo pipefail
slug="$1"; question="$2"; fps="${FPS:-12}"; bg="${BG:-0x171717}"
cd "$(dirname "$0")"
. ./env.sh
# A clean clone of this repository on main, already trusted in Claude Code. See README.md.
demo_repo="${DEMO_REPO:-$HOME/demo/clear-claude}"
demo_cd="${DEMO_CD:-~/demo/clear-claude}" # as typed in the tape, so no absolute path is committed
# Claude Code names a project's transcript folder after its native path.
project="$demo_repo"
if command -v cygpath > /dev/null; then project="$(cygpath -w "$demo_repo")"; fi
# An explicit font file: drawtext's fontconfig lookup crashes ffmpeg on Windows.
fontfile="${FONTFILE:-C\:/Windows/Fonts/consolab.ttf}"

tape() { # <arm> <claude command>
  cat > "$slug-$1.tape" <<TAPE
# $1 arm of: $question
# Generated by record-pair.sh. The hidden line only changes directory and switches CLAUDE.md
# discovery off; everything after Show is what the viewer sees being typed.
Output frames-$slug-$1/
Set Shell "bash"
Set FontSize 14
Set Width 690
Set Height 940
Set Padding 14
Set Framerate $fps
Set TypingSpeed 35ms
Hide
# VHS on Windows can drop the first keystroke; a leading space is harmless to bash.
Type " cd $demo_cd && export CLAUDE_CODE_DISABLE_CLAUDE_MDS=1 && clear"
Enter
Sleep 1s
Show
Type "$2"
Sleep 600ms
Enter
Sleep 8s
Type "$question"
Sleep 600ms
Enter
Sleep 26s
TAPE
}

if [ -z "${ASSEMBLE_ONLY:-}" ]; then
  tape before "claude --setting-sources project"
  tape after  "claude --setting-sources project --plugin-dir plugins/clear-claude"
  for arm in before after; do
    rm -rf "frames-$slug-$arm"
    vhs "$slug-$arm.tape" > "$slug-$arm.log" 2>&1
    node words.mjs "$project" > "$slug-$arm.words"
  done
fi

wb=$(cat "$slug-before.words"); wa=$(cat "$slug-after.words")
banner() { # <title> <colour> <words>
  echo "pad=iw:ih+36:0:36:color=0x101010,drawtext=fontfile='$fontfile':text='$1':fontcolor=$2:fontsize=17:x=16:y=10,drawtext=fontfile='$fontfile':text='$3 words':fontcolor=0x9A9A9A:fontsize=17:x=w-tw-16:y=10"
}
size() { ffprobe -v error -show_entries stream=width,height -of csv=p=0:s=x "frames-$slug-$1/frame-text-00001.png"; }

ffmpeg -v error -y \
  -f lavfi -i "color=c=$bg:s=$(size before):r=$fps" -framerate "$fps" -i "frames-$slug-before/frame-text-%05d.png" -framerate "$fps" -i "frames-$slug-before/frame-cursor-%05d.png" \
  -f lavfi -i "color=c=$bg:s=$(size after):r=$fps"  -framerate "$fps" -i "frames-$slug-after/frame-text-%05d.png"  -framerate "$fps" -i "frames-$slug-after/frame-cursor-%05d.png" \
  -filter_complex "[0][1]overlay=format=auto:shortest=1[a];[a][2]overlay=format=auto:shortest=1,$(banner 'BEFORE  Claude Code, no plugin' 0xE06C6C "$wb"),pad=iw+3:ih:0:0:color=0x3a3a3a[L];[3][4]overlay=format=auto:shortest=1[b];[b][5]overlay=format=auto:shortest=1,$(banner 'AFTER  + clear-claude plugin' 0x5FBF77 "$wa")[R];[L][R]hstack=shortest=1,split[x][y];[x]palettegen=stats_mode=full:max_colors=256[p];[y][p]paletteuse=dither=none:diff_mode=rectangle" \
  "$slug.gif"
echo "$slug: $wb -> $wa words"
ls -la "$slug.gif"
